<a href="https://colab.research.google.com/github/MUNIALO-DA/Airbnb-data-analyses/blob/main/webscrab_end_to_end.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import requests
from bs4 import BeautifulSoup
headers= {"user-agent":"mozilla/5.o(windows NT 10.0; Win64; *64) applewebkit/537.36 (KHTML, like Gecko) chrome/91.0.0.4472124 safari/537.6"}
url= "https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue"
response= requests.get(url, headers=headers, timeout=20)
print("Status code:", response.status_code)

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    print(soup.title)
else:
    print("The webpage request was not successful.")

Status code: 200
<title>List of largest companies in the United States by revenue - Wikipedia</title>

In [5]:
soup.find('table')

<table class="wikitable sortable" id="mwOw">
<caption id="mwPA"></caption>
<tbody id="mwPQ"><tr id="mwPg"><th id="mwPw">Rank</th>
<th id="mwQA">Name</th>
<th id="mwQQ">Industry</th>
<th id="mwQg">Revenue <br id="mwQw"/>(USD millions)</th>
<th id="mwRA">Revenue growth</th>
<th id="mwRQ">Employees</th>
<th id="mwRg">Headquarters</th></tr>
<tr id="mwRw">
<td id="mwSA">1</td>
<td id="mwSQ"><a href="https://en.wikipedia.org/wiki/Walmart" id="mwSg" rel="mw:WikiLink" title="Walmart">Walmart</a></td>
<td id="mwSw">Retail</td>
<td id="mwTA" style="text-align:center;">680,985</td>
<td id="mwTQ" style="text-align:center;"><span about="#mwt7" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwTg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt8" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwTw" style="display:none" typeof="mw:Transclusion"></span> 5.1%</td>
<td id="mwUA" style="text-align:center;">2,100,000</td>
<td id="mwUQ"><a href="https://en.wikipedia.org/wiki/Bentonville,_Arkansas" id="mwUg" rel="mw:WikiLink" title="Bentonville, Arkansas">Bentonville, Arkansas</a></td></tr>
<tr id="mwUw">
<td id="mwVA">2</td>
<td id="mwVQ"><a href="https://en.wikipedia.org/wiki/Amazon_(company)" id="mwVg" rel="mw:WikiLink" title="Amazon (company)">Amazon</a></td>
<td id="mwVw">Retail and cloud computing</td>
<td id="mwWA" style="text-align:center;">637,959</td>
<td id="mwWQ" style="text-align:center;"><span about="#mwt9" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwWg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt10" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwWw" style="display:none" typeof="mw:Transclusion"></span> 11.0%</td>
<td id="mwXA" style="text-align:center;">1,556,000</td>
<td id="mwXQ"><a href="https://en.wikipedia.org/wiki/Seattle" id="mwXg" rel="mw:WikiLink" title="Seattle">Seattle, Washington</a></td></tr>
<tr id="mwXw">
<td id="mwYA">3</td>
<td id="mwYQ"><a href="https://en.wikipedia.org/wiki/UnitedHealth_Group" id="mwYg" rel="mw:WikiLink" title="UnitedHealth Group">UnitedHealth Group</a></td>
<td id="mwYw">Healthcare</td>
<td id="mwZA" style="text-align:center;">400,278</td>
<td id="mwZQ" style="text-align:center;"><span about="#mwt11" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwZg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt12" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwZw" style="display:none" typeof="mw:Transclusion"></span> 7.7%</td>
<td id="mwaA" style="text-align:center;">400,000</td>
<td id="mwaQ"><a href="https://en.wikipedia.org/wiki/Minnetonka,_Minnesota" id="mwag" rel="mw:WikiLink" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a></td></tr>
<tr id="mwaw">
<td id="mwbA">4</td>
<td id="mwbQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Apple_Inc" id="mwbg" rel="mw:WikiLink" title="Apple Inc">Apple</a></td>
<td id="mwbw">Technology</td>
<td id="mwcA" style="text-align:center;">391,035</td>
<td id="mwcQ" style="text-align:center;"><span about="#mwt13" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwcg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt14" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwcw" style="display:none" typeof="mw:Transclusion"></span> 2.0%</td>
<td id="mwdA" style="text-align:center;">164,000</td>
<td id="mwdQ"><a href="https://en.wikipedia.org/wiki/Cupertino,_California" id="mwdg" rel="mw:WikiLink" title="Cupertino, California">Cupertino, California</a></td></tr>
<tr id="mwdw">
<td id="mweA">5</td>
<td id="mweQ"><a href="https://en.wikipedia.org/wiki/CVS_Health" id="mweg" rel="mw:WikiLink" title="CVS Health">CVS Health</a></td>
<td id="mwew">Healthcare</td>
<td id="mwfA" style="text-align:center;">372,809</td>
<td id="mwfQ" style="text-align:center;"><span about="#mwt15" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwfg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt16" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwfw" style="display:none" typeof="mw:Transclusion"></span> 4.2%</td>
<td id="mwgA" style="text-align:center;">259,500</td>
<td id="mwgQ"><a href="https://en.wikipedia.org/wiki/Woonsocket,_Rhode_Island" id="mwgg" rel="mw:WikiLink" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a></td></tr>
<tr id="mwgw">
<td id="mwhA">6</td>
<td id="mwhQ"><a href="https://en.wikipedia.org/wiki/Berkshire_Hathaway" id="mwhg" rel="mw:WikiLink" title="Berkshire Hathaway">Berkshire Hathaway</a></td>
<td id="mwhw">Conglomerate</td>
<td id="mwiA" style="text-align:center;">371,433</td>
<td id="mwiQ" style="text-align:center;"><span about="#mwt17" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwig" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt18" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwiw" style="display:none" typeof="mw:Transclusion"></span> 1.9%</td>
<td id="mwjA" style="text-align:center;">392,400</td>
<td id="mwjQ"><a href="https://en.wikipedia.org/wiki/Omaha,_Nebraska" id="mwjg" rel="mw:WikiLink" title="Omaha, Nebraska">Omaha, Nebraska</a></td></tr>
<tr id="mwjw">
<td id="mwkA">7</td>
<td id="mwkQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Alphabet_Inc" id="mwkg" rel="mw:WikiLink" title="Alphabet Inc">Alphabet</a></td>
<td id="mwkw">Technology and cloud computing</td>
<td id="mwlA" style="text-align:center;">350,018</td>
<td id="mwlQ" style="text-align:center;"><span about="#mwt19" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwlg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt20" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwlw" style="display:none" typeof="mw:Transclusion"></span> 13.9%</td>
<td id="mwmA" style="text-align:center;">183,323</td>
<td id="mwmQ"><a href="https://en.wikipedia.org/wiki/Mountain_View,_California" id="mwmg" rel="mw:WikiLink" title="Mountain View, California">Mountain View, California</a></td></tr>
<tr id="mwmw">
<td id="mwnA">8</td>
<td id="mwnQ"><a href="https://en.wikipedia.org/wiki/ExxonMobil" id="mwng" rel="mw:WikiLink" title="ExxonMobil">Exxon Mobil</a></td>
<td id="mwnw">Petroleum</td>
<td id="mwoA" style="text-align:center;">349,595</td>
<td id="mwoQ" style="text-align:center;"><span about="#mwt21" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwog" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt22" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwow" style="display:none" typeof="mw:Transclusion"></span> 1.5%</td>
<td id="mwpA" style="text-align:center;">60,900</td>
<td id="mwpQ"><a href="https://en.wikipedia.org/wiki/Spring,_Texas" id="mwpg" rel="mw:WikiLink" title="Spring, Texas">Spring, Texas</a></td></tr>
<tr id="mwpw">
<td id="mwqA">9</td>
<td id="mwqQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/McKesson_Corporation" id="mwqg" rel="mw:WikiLink" title="McKesson Corporation">McKesson Corporation</a></td>
<td id="mwqw">Healthcare</td>
<td id="mwrA" style="text-align:center;">308,951</td>
<td id="mwrQ" style="text-align:center;"><span about="#mwt23" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwrg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt24" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwrw" style="display:none" typeof="mw:Transclusion"></span> 11.7%</td>
<td id="mwsA" style="text-align:center;">48,000</td>
<td id="mwsQ"><a href="https://en.wikipedia.org/wiki/Irving,_Texas" id="mwsg" rel="mw:WikiLink" title="Irving, Texas">Irving, Texas</a></td></tr>
<tr id="mwsw">
<td id="mwtA">10</td>
<td id="mwtQ"><a href="https://en.wikipedia.org/wiki/Cencora" id="mwtg" rel="mw:WikiLink" title="Cencora">Cencora</a></td>
<td id="mwtw">Pharmacy wholesale</td>
<td id="mwuA" style="text-align:center;">293,959</td>
<td id="mwuQ" style="text-align:center;"><span about="#mwt25" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwug" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt26" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwuw" style="display:none" typeof="mw:Transclusion"></span> 12.1%</td>
<td id="mwvA" style="text-align:center;">44,000</td>
<td id="mwvQ"><a href="https://en.wikipedia.org/wiki/Conshohocken,_Pennsylvania" id="mwvg" rel="mw:WikiLink" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a></td></tr>
<tr id="mwvw">
<td id="mwwA">11</td>
<td id="mwwQ"><a href="https://en.wikipedia.org/wiki/JPMorgan_Chase" id="mwwg" rel="mw:WikiLink" title="JPMorgan Chase">JPMorgan Chase</a></td>
<td id="mwww">Financials</td>
<td id="mwxA" style="text-align:center;">278,906</td>
<td id="mwxQ" style="text-align:center;"><span about="#mwt27" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwxg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt28" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwxw" style="display:none" typeof="mw:Transclusion"></span> 16.5%</td>
<td id="mwyA" style="text-align:center;">317,233</td>
<td id="mwyQ"><a href="https://en.wikipedia.org/wiki/New_York_City" id="mwyg" rel="mw:WikiLink" title="New York City">New York City, New York</a></td></tr>
<tr id="mwyw">
<td id="mwzA">12</td>
<td id="mwzQ"><a href="https://en.wikipedia.org/wiki/Costco" id="mwzg" rel="mw:WikiLink" title="Costco">Costco Wholesale</a></td>
<td id="mwzw">Retail</td>
<td id="mw0A" style="text-align:center;">254,453</td>
<td id="mw0Q" style="text-align:center;"><span about="#mwt29" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mw0g" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt30" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mw0w" style="display:none" typeof="mw:Transclusion"></span> 5.0%</td>
<td id="mw1A" style="text-align:center;">333,000</td>
<td id="mw1Q"><a href="https://en.wikipedia.org/wiki/Issaquah,_Washington" id="mw1g" rel="mw:WikiLink" title="Issaquah, Washington">Issaquah, Washington</a></td></tr>
<tr id="mw1w">
<td id="mw2A">13</td>
<td id="mw2Q"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Cigna" id="mw2g" rel="mw:WikiLink" title="Cigna">Cigna</a></td>
<td id="mw2w">Health insurance</td>
<td id="mw3A" style="text-align:center;">247,121</td>

In [7]:
soup.find_all("table")[1]

<table class="wikitable sortable" id="mwBQA">
<tbody id="mwBQE"><tr id="mwBQI"><th id="mwBQM">Rank</th>
<th id="mwBQQ">Name</th>
<th id="mwBQU">Industry</th>
<th id="mwBQY">Revenue <br id="mwBQc"/>(USD billions)</th>
<th id="mwBQg">Employees</th>
<th id="mwBQk">Headquarters</th></tr>
<tr id="mwBQo">
<td id="mwBQs">1</td>
<td id="mwBQw"><a href="https://en.wikipedia.org/wiki/Cargill" id="mwBQ0" rel="mw:WikiLink" title="Cargill">Cargill</a></td>
<td id="mwBQ4">Food &amp; Drink</td>
<td id="mwBQ8" style="text-align:center;">154</td>
<td id="mwBRA" style="text-align:center;">155,000</td>
<td id="mwBRE"><a href="https://en.wikipedia.org/wiki/Minnetonka,_Minnesota" id="mwBRI" rel="mw:WikiLink" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a></td></tr>
<tr id="mwBRM">
<td id="mwBRQ">2</td>
<td id="mwBRU"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Koch_Industries" id="mwBRY" rel="mw:WikiLink" title="Koch Industries">Koch</a></td>
<td id="mwBRc">Multicompany</td>
<td id="mwBRg" style="text-align:center;">125</td>
<td id="mwBRk" style="text-align:center;">120,000</td>
<td id="mwBRo"><a href="https://en.wikipedia.org/wiki/Wichita,_Kansas" id="mwBRs" rel="mw:WikiLink" title="Wichita, Kansas">Wichita, Kansas</a></td></tr>
<tr id="mwBRw">
<td id="mwBR0">3</td>
<td id="mwBR4"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Publix_Super_Markets" id="mwBR8" rel="mw:WikiLink" title="Publix Super Markets">Publix Super Markets</a></td>
<td id="mwBSA">Food Markets</td>
<td id="mwBSE" style="text-align:center;">59.7</td>
<td id="mwBSI" style="text-align:center;">260,000</td>
<td id="mwBSM"><a href="https://en.wikipedia.org/wiki/Lakeland,_Florida" id="mwBSQ" rel="mw:WikiLink" title="Lakeland, Florida">Lakeland, Florida</a></td></tr>
<tr id="mwBSU">
<td id="mwBSY">4</td>
<td id="mwBSc"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Mars,_Incorporated" id="mwBSg" rel="mw:WikiLink" title="Mars, Incorporated">Mars</a></td>
<td id="mwBSk">Food &amp; Drink</td>
<td id="mwBSo" style="text-align:center;">55</td>
<td id="mwBSs" style="text-align:center;">150,000</td>
<td id="mwBSw"><a href="https://en.wikipedia.org/wiki/McLean,_Virginia" id="mwBS0" rel="mw:WikiLink" title="McLean, Virginia">McLean, Virginia</a></td></tr>
<tr id="mwBS4">
<td id="mwBS8">5</td>
<td id="mwBTA"><a href="https://en.wikipedia.org/wiki/H-E-B" id="mwBTE" rel="mw:WikiLink" title="H-E-B">H-E-B Grocery Company</a></td>
<td id="mwBTI">Food Markets</td>
<td id="mwBTM" style="text-align:center;">49.57</td>
<td id="mwBTQ" style="text-align:center;">175,000</td>
<td id="mwBTU"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/San_Antonio,_Texas" id="mwBTY" rel="mw:WikiLink" title="San Antonio, Texas">San Antonio, Texas</a></td></tr>
<tr id="mwBTc">
<td id="mwBTg">6</td>
<td id="mwBTk"><a href="https://en.wikipedia.org/wiki/Reyes_Holdings" id="mwBTo" rel="mw:WikiLink" title="Reyes Holdings">Reyes Holdings</a></td>
<td id="mwBTs">Food, Drink &amp; Tobacco</td>
<td id="mwBTw" style="text-align:center;">44</td>
<td id="mwBT0" style="text-align:center;">36,000</td>
<td id="mwBT4"><a href="https://en.wikipedia.org/wiki/Rosemont,_Illinois" id="mwBT8" rel="mw:WikiLink" title="Rosemont, Illinois">Rosemont, Illinois</a></td></tr>
<tr id="mwBUA">
<td id="mwBUE">7</td>
<td id="mwBUI"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Enterprise_Mobility" id="mwBUM" rel="mw:WikiLink" title="Enterprise Mobility">Enterprise Mobility</a></td>
<td id="mwBUQ">Services</td>
<td id="mwBUU" style="text-align:center;">38</td>
<td id="mwBUY" style="text-align:center;">100,000</td>
<td id="mwBUc"><a href="https://en.wikipedia.org/wiki/Clayton,_Missouri" id="mwBUg" rel="mw:WikiLink" title="Clayton, Missouri">Clayton, Missouri</a></td></tr>
<tr id="mwBUk">
<td id="mwBUo">8</td>
<td id="mwBUs"><a href="https://en.wikipedia.org/wiki/Fidelity_Investments" id="mwBUw" rel="mw:WikiLink" title="Fidelity Investments">Fidelity Investments</a></td>
<td id="mwBU0">Insurance</td>
<td id="mwBU4" style="text-align:center;">32.7</td>
<td id="mwBU8" style="text-align:center;">78,000</td>
<td id="mwBVA"><a href="https://en.wikipedia.org/wiki/Boston" id="mwBVE" rel="mw:WikiLink" title="Boston">Boston, Massachusetts</a></td></tr>
<tr id="mwBVI">
<td id="mwBVM">9</td>
<td id="mwBVQ"><a href="https://en.wikipedia.org/wiki/Southern_Glazer's_Wine_and_Spirits" id="mwBVU" rel="mw:WikiLink" title="Southern Glazer's Wine and Spirits">Southern Glazer's Wine &amp; Spirits</a></td>
<td id="mwBVY">Food, Drink &amp; Tobacco</td>
<td id="mwBVc" style="text-align:center;">25</td>
<td id="mwBVg" style="text-align:center;">24,000</td>
<td id="mwBVk"><a href="https://en.wikipedia.org/wiki/Miramar,_Florida" id="mwBVo" rel="mw:WikiLink" title="Miramar, Florida">Miramar, Florida</a></td></tr>
<tr id="mwBVs">
<td id="mwBVw">10</td>
<td id="mwBV0"><a href="https://en.wikipedia.org/wiki/Cox_Enterprises" id="mwBV4" rel="mw:WikiLink" title="Cox Enterprises">Cox Enterprises</a></td>
<td id="mwBV8">Media</td>
<td id="mwBWA" style="text-align:center;">23.5</td>
<td id="mwBWE" style="text-align:center;">50,000</td>
<td id="mwBWI"><a href="https://en.wikipedia.org/wiki/Atlanta" id="mwBWM" rel="mw:WikiLink" title="Atlanta">Atlanta, Georgia</a></td></tr>
</tbody></table>

In [9]:
soup.find("table", class_="wikitable sortable")

<table class="wikitable sortable" id="mwOw">
<caption id="mwPA"></caption>
<tbody id="mwPQ"><tr id="mwPg"><th id="mwPw">Rank</th>
<th id="mwQA">Name</th>
<th id="mwQQ">Industry</th>
<th id="mwQg">Revenue <br id="mwQw"/>(USD millions)</th>
<th id="mwRA">Revenue growth</th>
<th id="mwRQ">Employees</th>
<th id="mwRg">Headquarters</th></tr>
<tr id="mwRw">
<td id="mwSA">1</td>
<td id="mwSQ"><a href="https://en.wikipedia.org/wiki/Walmart" id="mwSg" rel="mw:WikiLink" title="Walmart">Walmart</a></td>
<td id="mwSw">Retail</td>
<td id="mwTA" style="text-align:center;">680,985</td>
<td id="mwTQ" style="text-align:center;"><span about="#mwt7" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwTg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt8" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwTw" style="display:none" typeof="mw:Transclusion"></span> 5.1%</td>
<td id="mwUA" style="text-align:center;">2,100,000</td>
<td id="mwUQ"><a href="https://en.wikipedia.org/wiki/Bentonville,_Arkansas" id="mwUg" rel="mw:WikiLink" title="Bentonville, Arkansas">Bentonville, Arkansas</a></td></tr>
<tr id="mwUw">
<td id="mwVA">2</td>
<td id="mwVQ"><a href="https://en.wikipedia.org/wiki/Amazon_(company)" id="mwVg" rel="mw:WikiLink" title="Amazon (company)">Amazon</a></td>
<td id="mwVw">Retail and cloud computing</td>
<td id="mwWA" style="text-align:center;">637,959</td>
<td id="mwWQ" style="text-align:center;"><span about="#mwt9" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwWg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt10" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwWw" style="display:none" typeof="mw:Transclusion"></span> 11.0%</td>
<td id="mwXA" style="text-align:center;">1,556,000</td>
<td id="mwXQ"><a href="https://en.wikipedia.org/wiki/Seattle" id="mwXg" rel="mw:WikiLink" title="Seattle">Seattle, Washington</a></td></tr>
<tr id="mwXw">
<td id="mwYA">3</td>
<td id="mwYQ"><a href="https://en.wikipedia.org/wiki/UnitedHealth_Group" id="mwYg" rel="mw:WikiLink" title="UnitedHealth Group">UnitedHealth Group</a></td>
<td id="mwYw">Healthcare</td>
<td id="mwZA" style="text-align:center;">400,278</td>
<td id="mwZQ" style="text-align:center;"><span about="#mwt11" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwZg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt12" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwZw" style="display:none" typeof="mw:Transclusion"></span> 7.7%</td>
<td id="mwaA" style="text-align:center;">400,000</td>
<td id="mwaQ"><a href="https://en.wikipedia.org/wiki/Minnetonka,_Minnesota" id="mwag" rel="mw:WikiLink" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a></td></tr>
<tr id="mwaw">
<td id="mwbA">4</td>
<td id="mwbQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Apple_Inc" id="mwbg" rel="mw:WikiLink" title="Apple Inc">Apple</a></td>
<td id="mwbw">Technology</td>
<td id="mwcA" style="text-align:center;">391,035</td>
<td id="mwcQ" style="text-align:center;"><span about="#mwt13" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwcg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt14" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwcw" style="display:none" typeof="mw:Transclusion"></span> 2.0%</td>
<td id="mwdA" style="text-align:center;">164,000</td>
<td id="mwdQ"><a href="https://en.wikipedia.org/wiki/Cupertino,_California" id="mwdg" rel="mw:WikiLink" title="Cupertino, California">Cupertino, California</a></td></tr>
<tr id="mwdw">
<td id="mweA">5</td>
<td id="mweQ"><a href="https://en.wikipedia.org/wiki/CVS_Health" id="mweg" rel="mw:WikiLink" title="CVS Health">CVS Health</a></td>
<td id="mwew">Healthcare</td>
<td id="mwfA" style="text-align:center;">372,809</td>
<td id="mwfQ" style="text-align:center;"><span about="#mwt15" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwfg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt16" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwfw" style="display:none" typeof="mw:Transclusion"></span> 4.2%</td>
<td id="mwgA" style="text-align:center;">259,500</td>
<td id="mwgQ"><a href="https://en.wikipedia.org/wiki/Woonsocket,_Rhode_Island" id="mwgg" rel="mw:WikiLink" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a></td></tr>
<tr id="mwgw">
<td id="mwhA">6</td>
<td id="mwhQ"><a href="https://en.wikipedia.org/wiki/Berkshire_Hathaway" id="mwhg" rel="mw:WikiLink" title="Berkshire Hathaway">Berkshire Hathaway</a></td>
<td id="mwhw">Conglomerate</td>
<td id="mwiA" style="text-align:center;">371,433</td>
<td id="mwiQ" style="text-align:center;"><span about="#mwt17" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwig" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt18" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwiw" style="display:none" typeof="mw:Transclusion"></span> 1.9%</td>
<td id="mwjA" style="text-align:center;">392,400</td>
<td id="mwjQ"><a href="https://en.wikipedia.org/wiki/Omaha,_Nebraska" id="mwjg" rel="mw:WikiLink" title="Omaha, Nebraska">Omaha, Nebraska</a></td></tr>
<tr id="mwjw">
<td id="mwkA">7</td>
<td id="mwkQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Alphabet_Inc" id="mwkg" rel="mw:WikiLink" title="Alphabet Inc">Alphabet</a></td>
<td id="mwkw">Technology and cloud computing</td>
<td id="mwlA" style="text-align:center;">350,018</td>
<td id="mwlQ" style="text-align:center;"><span about="#mwt19" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwlg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt20" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwlw" style="display:none" typeof="mw:Transclusion"></span> 13.9%</td>
<td id="mwmA" style="text-align:center;">183,323</td>
<td id="mwmQ"><a href="https://en.wikipedia.org/wiki/Mountain_View,_California" id="mwmg" rel="mw:WikiLink" title="Mountain View, California">Mountain View, California</a></td></tr>
<tr id="mwmw">
<td id="mwnA">8</td>
<td id="mwnQ"><a href="https://en.wikipedia.org/wiki/ExxonMobil" id="mwng" rel="mw:WikiLink" title="ExxonMobil">Exxon Mobil</a></td>
<td id="mwnw">Petroleum</td>
<td id="mwoA" style="text-align:center;">349,595</td>
<td id="mwoQ" style="text-align:center;"><span about="#mwt21" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwog" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt22" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwow" style="display:none" typeof="mw:Transclusion"></span> 1.5%</td>
<td id="mwpA" style="text-align:center;">60,900</td>
<td id="mwpQ"><a href="https://en.wikipedia.org/wiki/Spring,_Texas" id="mwpg" rel="mw:WikiLink" title="Spring, Texas">Spring, Texas</a></td></tr>
<tr id="mwpw">
<td id="mwqA">9</td>
<td id="mwqQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/McKesson_Corporation" id="mwqg" rel="mw:WikiLink" title="McKesson Corporation">McKesson Corporation</a></td>
<td id="mwqw">Healthcare</td>
<td id="mwrA" style="text-align:center;">308,951</td>
<td id="mwrQ" style="text-align:center;"><span about="#mwt23" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwrg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt24" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwrw" style="display:none" typeof="mw:Transclusion"></span> 11.7%</td>
<td id="mwsA" style="text-align:center;">48,000</td>
<td id="mwsQ"><a href="https://en.wikipedia.org/wiki/Irving,_Texas" id="mwsg" rel="mw:WikiLink" title="Irving, Texas">Irving, Texas</a></td></tr>
<tr id="mwsw">
<td id="mwtA">10</td>
<td id="mwtQ"><a href="https://en.wikipedia.org/wiki/Cencora" id="mwtg" rel="mw:WikiLink" title="Cencora">Cencora</a></td>
<td id="mwtw">Pharmacy wholesale</td>
<td id="mwuA" style="text-align:center;">293,959</td>
<td id="mwuQ" style="text-align:center;"><span about="#mwt25" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwug" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt26" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwuw" style="display:none" typeof="mw:Transclusion"></span> 12.1%</td>
<td id="mwvA" style="text-align:center;">44,000</td>
<td id="mwvQ"><a href="https://en.wikipedia.org/wiki/Conshohocken,_Pennsylvania" id="mwvg" rel="mw:WikiLink" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a></td></tr>
<tr id="mwvw">
<td id="mwwA">11</td>
<td id="mwwQ"><a href="https://en.wikipedia.org/wiki/JPMorgan_Chase" id="mwwg" rel="mw:WikiLink" title="JPMorgan Chase">JPMorgan Chase</a></td>
<td id="mwww">Financials</td>
<td id="mwxA" style="text-align:center;">278,906</td>
<td id="mwxQ" style="text-align:center;"><span about="#mwt27" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwxg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt28" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwxw" style="display:none" typeof="mw:Transclusion"></span> 16.5%</td>
<td id="mwyA" style="text-align:center;">317,233</td>
<td id="mwyQ"><a href="https://en.wikipedia.org/wiki/New_York_City" id="mwyg" rel="mw:WikiLink" title="New York City">New York City, New York</a></td></tr>
<tr id="mwyw">
<td id="mwzA">12</td>
<td id="mwzQ"><a href="https://en.wikipedia.org/wiki/Costco" id="mwzg" rel="mw:WikiLink" title="Costco">Costco Wholesale</a></td>
<td id="mwzw">Retail</td>
<td id="mw0A" style="text-align:center;">254,453</td>
<td id="mw0Q" style="text-align:center;"><span about="#mwt29" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mw0g" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span about="#mwt30" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mw0w" style="display:none" typeof="mw:Transclusion"></span> 5.0%</td>
<td id="mw1A" style="text-align:center;">333,000</td>
<td id="mw1Q"><a href="https://en.wikipedia.org/wiki/Issaquah,_Washington" id="mw1g" rel="mw:WikiLink" title="Issaquah, Washington">Issaquah, Washington</a></td></tr>
<tr id="mw1w">
<td id="mw2A">13</td>
<td id="mw2Q"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Cigna" id="mw2g" rel="mw:WikiLink" title="Cigna">Cigna</a></td>
<td id="mw2w">Health insurance</td>
<td id="mw3A" style="text-align:center;">247,121</td>

In [12]:
table= soup.find_all("table")[1]
print(table)

<table class="wikitable sortable" id="mwBQA">
<tbody id="mwBQE"><tr id="mwBQI"><th id="mwBQM">Rank</th>
<th id="mwBQQ">Name</th>
<th id="mwBQU">Industry</th>
<th id="mwBQY">Revenue <br id="mwBQc"/>(USD billions)</th>
<th id="mwBQg">Employees</th>
<th id="mwBQk">Headquarters</th></tr>
<tr id="mwBQo">
<td id="mwBQs">1</td>
<td id="mwBQw"><a href="https://en.wikipedia.org/wiki/Cargill" id="mwBQ0" rel="mw:WikiLink" title="Cargill">Cargill</a></td>
<td id="mwBQ4">Food &amp; Drink</td>
<td id="mwBQ8" style="text-align:center;">154</td>
<td id="mwBRA" style="text-align:center;">155,000</td>
<td id="mwBRE"><a href="https://en.wikipedia.org/wiki/Minnetonka,_Minnesota" id="mwBRI" rel="mw:WikiLink" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a></td></tr>
<tr id="mwBRM">
<td id="mwBRQ">2</td>
<td id="mwBRU"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Koch_Industries" id="mwBRY" rel="mw:WikiLink" title="Koch Industries">Koch</a></td>
<td id="mwBRc">Multicompany</td>
<td id="mwBRg" style="text-align:center;">125</td>
<td id="mwBRk" style="text-align:center;">120,000</td>
<td id="mwBRo"><a href="https://en.wikipedia.org/wiki/Wichita,_Kansas" id="mwBRs" rel="mw:WikiLink" title="Wichita, Kansas">Wichita, Kansas</a></td></tr>
<tr id="mwBRw">
<td id="mwBR0">3</td>
<td id="mwBR4"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Publix_Super_Markets" id="mwBR8" rel="mw:WikiLink" title="Publix Super Markets">Publix Super Markets</a></td>
<td id="mwBSA">Food Markets</td>
<td id="mwBSE" style="text-align:center;">59.7</td>
<td id="mwBSI" style="text-align:center;">260,000</td>
<td id="mwBSM"><a href="https://en.wikipedia.org/wiki/Lakeland,_Florida" id="mwBSQ" rel="mw:WikiLink" title="Lakeland, Florida">Lakeland, Florida</a></td></tr>
<tr id="mwBSU">
<td id="mwBSY">4</td>
<td id="mwBSc"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Mars,_Incorporated" id="mwBSg" rel="mw:WikiLink" title="Mars, Incorporated">Mars</a></td>
<td id="mwBSk">Food &amp; Drink</td>
<td id="mwBSo" style="text-align:center;">55</td>
<td id="mwBSs" style="text-align:center;">150,000</td>
<td id="mwBSw"><a href="https://en.wikipedia.org/wiki/McLean,_Virginia" id="mwBS0" rel="mw:WikiLink" title="McLean, Virginia">McLean, Virginia</a></td></tr>
<tr id="mwBS4">
<td id="mwBS8">5</td>
<td id="mwBTA"><a href="https://en.wikipedia.org/wiki/H-E-B" id="mwBTE" rel="mw:WikiLink" title="H-E-B">H-E-B Grocery Company</a></td>
<td id="mwBTI">Food Markets</td>
<td id="mwBTM" style="text-align:center;">49.57</td>
<td id="mwBTQ" style="text-align:center;">175,000</td>
<td id="mwBTU"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/San_Antonio,_Texas" id="mwBTY" rel="mw:WikiLink" title="San Antonio, Texas">San Antonio, Texas</a></td></tr>
<tr id="mwBTc">
<td id="mwBTg">6</td>
<td id="mwBTk"><a href="https://en.wikipedia.org/wiki/Reyes_Holdings" id="mwBTo" rel="mw:WikiLink" title="Reyes Holdings">Reyes Holdings</a></td>
<td id="mwBTs">Food, Drink &amp; Tobacco</td>
<td id="mwBTw" style="text-align:center;">44</td>
<td id="mwBT0" style="text-align:center;">36,000</td>
<td id="mwBT4"><a href="https://en.wikipedia.org/wiki/Rosemont,_Illinois" id="mwBT8" rel="mw:WikiLink" title="Rosemont, Illinois">Rosemont, Illinois</a></td></tr>
<tr id="mwBUA">
<td id="mwBUE">7</td>
<td id="mwBUI"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Enterprise_Mobility" id="mwBUM" rel="mw:WikiLink" title="Enterprise Mobility">Enterprise Mobility</a></td>
<td id="mwBUQ">Services</td>
<td id="mwBUU" style="text-align:center;">38</td>
<td id="mwBUY" style="text-align:center;">100,000</td>
<td id="mwBUc"><a href="https://en.wikipedia.org/wiki/Clayton,_Missouri" id="mwBUg" rel="mw:WikiLink" title="Clayton, Missouri">Clayton, Missouri</a></td></tr>
<tr id="mwBUk">
<td id="mwBUo">8</td>
<td id="mwBUs"><a href="https://en.wikipedia.org/wiki/Fidelity_Investments" id="mwBUw" rel="mw:WikiLink" title="Fidelity Investments">Fidelity Investments</a></td>
<td id="mwBU0">Insurance</td>
<td id="mwBU4" style="text-align:center;">32.7</td>
<td id="mwBU8" style="text-align:center;">78,000</td>
<td id="mwBVA"><a href="https://en.wikipedia.org/wiki/Boston" id="mwBVE" rel="mw:WikiLink" title="Boston">Boston, Massachusetts</a></td></tr>
<tr id="mwBVI">
<td id="mwBVM">9</td>
<td id="mwBVQ"><a href="https://en.wikipedia.org/wiki/Southern_Glazer's_Wine_and_Spirits" id="mwBVU" rel="mw:WikiLink" title="Southern Glazer's Wine and Spirits">Southern Glazer's Wine &amp; Spirits</a></td>
<td id="mwBVY">Food, Drink &amp; Tobacco</td>
<td id="mwBVc" style="text-align:center;">25</td>
<td id="mwBVg" style="text-align:center;">24,000</td>
<td id="mwBVk"><a href="https://en.wikipedia.org/wiki/Miramar,_Florida" id="mwBVo" rel="mw:WikiLink" title="Miramar, Florida">Miramar, Florida</a></td></tr>
<tr id="mwBVs">
<td id="mwBVw">10</td>
<td id="mwBV0"><a href="https://en.wikipedia.org/wiki/Cox_Enterprises" id="mwBV4" rel="mw:WikiLink" title="Cox Enterprises">Cox Enterprises</a></td>
<td id="mwBV8">Media</td>
<td id="mwBWA" style="text-align:center;">23.5</td>
<td id="mwBWE" style="text-align:center;">50,000</td>
<td id="mwBWI"><a href="https://en.wikipedia.org/wiki/Atlanta" id="mwBWM" rel="mw:WikiLink" title="Atlanta">Atlanta, Georgia</a></td></tr>
</tbody></table>

In [13]:
world_titles= table.find_all("th")
world_titles

[<th id="mwBQM">Rank</th>,
 <th id="mwBQQ">Name</th>,
 <th id="mwBQU">Industry</th>,
 <th id="mwBQY">Revenue <br id="mwBQc"/>(USD billions)</th>,
 <th id="mwBQg">Employees</th>,
 <th id="mwBQk">Headquarters</th>]

In [14]:
world_titles=[title.text.strip() for title in world_titles]
print(world_titles)

['Rank', 'Name', 'Industry', 'Revenue (USD billions)', 'Employees', 'Headquarters']

In [15]:
import pandas as pd
df= pd.DataFrame(columns= world_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD billions), Employees, Headquarters]
Index: []

In [20]:
column_data = table.find_all("td")
for row in column_data [1:]:
    print(row.text)
    individual_row_data=[data.text.strip() for data in row]
    print(individual_row_data)

Cargill
['Cargill']
Food & Drink
['Food & Drink']
154
['154']
155,000
['155,000']
Minnetonka, Minnesota
['Minnetonka, Minnesota']
2
['2']
Koch
['Koch']
Multicompany
['Multicompany']
125
['125']
120,000
['120,000']
Wichita, Kansas
['Wichita, Kansas']
3
['3']
Publix Super Markets
['Publix Super Markets']
Food Markets
['Food Markets']
59.7
['59.7']
260,000
['260,000']
Lakeland, Florida
['Lakeland, Florida']
4
['4']
Mars
['Mars']
Food & Drink
['Food & Drink']
55
['55']
150,000
['150,000']
McLean, Virginia
['McLean, Virginia']
5
['5']
H-E-B Grocery Company
['H-E-B Grocery Company']
Food Markets
['Food Markets']
49.57
['49.57']
175,000
['175,000']
San Antonio, Texas
['San Antonio, Texas']
6
['6']
Reyes Holdings
['Reyes Holdings']
Food, Drink & Tobacco
['Food, Drink & Tobacco']
44
['44']
36,000
['36,000']
Rosemont, Illinois
['Rosemont, Illinois']
7
['7']
Enterprise Mobility
['Enterprise Mobility']
Services
['Services']
38
['38']
100,000
['100,000']
Clayton, Missouri
['Clayton, Missouri']
8
['8']
Fidelity Investments
['Fidelity Investments']
Insurance
['Insurance']
32.7
['32.7']
78,000
['78,000']
Boston, Massachusetts
['Boston, Massachusetts']
9
['9']
Southern Glazer's Wine & Spirits
["Southern Glazer's Wine & Spirits"]
Food, Drink & Tobacco
['Food, Drink & Tobacco']
25
['25']
24,000
['24,000']
Miramar, Florida
['Miramar, Florida']
10
['10']
Cox Enterprises
['Cox Enterprises']
Media
['Media']
23.5
['23.5']
50,000
['50,000']
Atlanta, Georgia
['Atlanta, Georgia']

In [23]:
# Find all rows in the table
rows = table.find_all('tr')

# Loop through each row starting from index 1 (skipping header)
for row in rows[1:]:
    # Find all table data cells in this specific row
    row_data = row.find_all('td')
    # Extract and clean text from each cell
    individual_row_data = [data.text.strip() for data in row_data]

    # Only add to df if the row is not empty and matches the columns length
    if len(individual_row_data) == len(df.columns):
        length = len(df)
        df.loc[length] = individual_row_data

df

,Rank,Name,Industry,Revenue (USD billions),Employees,Headquarters
0,1,Cargill,Food & Drink,154,"155,000","Minnetonka, Minnesota"
1,2,Koch,Multicompany,125,"120,000","Wichita, Kansas"
2,3,Publix Super Markets,Food Markets,59.7,"260,000","Lakeland, Florida"
3,4,Mars,Food & Drink,55,"150,000","McLean, Virginia"
4,5,H-E-B Grocery Company,Food Markets,49.57,"175,000","San Antonio, Texas"
5,6,Reyes Holdings,"Food, Drink & Tobacco",44,"36,000","Rosemont, Illinois"
6,7,Enterprise Mobility,Services,38,"100,000","Clayton, Missouri"
7,8,Fidelity Investments,Insurance,32.7,"78,000","Boston, Massachusetts"
8,9,Southern Glazer's Wine & Spirits,"Food, Drink & Tobacco",25,"24,000","Miramar, Florida"
9,10,Cox Enterprises,Media,23.5,"50,000","Atlanta, Georgia"

In [25]:
df.to_csv(r"C:\data analysis docs\New folder\companies.csv", index=False)